### ISSUE TITLE
[AMP Components in Firefox][NF]_[Components_amp sidebar] Enable experiment button is greyed out

### ISSUE THREAD

**Issue by ampff** [ampproject/amp-by-example#1053]
Enable experiment button is greyed out in Components amp sidebar .Is this intended?
1.Go to https://ampbyexample.com/
2.Tap on Components
3.Tap on amp-sidebar and observe experiment button greyed out in experiment box
Observed result: Experiment button greyed out and non responsive
Expected results: Experiment button button should be responsive
Device(s):
Mac os desktop
Firefox :57.0.4 (64-bit)
Screenshot:https://screenshot.googleplex.com/kvAV901BCQS

**Comment by kul3r4** [comment]
Thanks for spotting this!

**Comment by kul3r4** [comment]
Checked this again: even if `amp-sidebar` is not experimental, we kept it that way because AMP does not allow 2 `amp-sidebar` in the same page but this is needed for this example.
Reason why you see the button grey is because you probably already pushed it. Clean your cookies and you'll see the button clickable again.
