### ISSUE TITLE
Geolocation with amp-list does not work anymore

### ISSUE THREAD

**Issue by Svenmay** [ampproject/amp-by-example#1340]
**Describe the bug**

**To Reproduce**
1. Go to 'https://ampbyexample.com/advanced/geolocation_with_amp-list/preview/'
2. Check network tab, watch for call to 'https://caramel-wolf.glitch.me//location-specific-results.json?__amp_source_origin=https%3A%2F%2Fampbyexample.com'....empty response.

**Expected behavior**
https://caramel-wolf.glitch.me//location-specific-results.json?__amp_source_origin=https%3A%2F%2Fampbyexample.com should return some results.

**Screenshots**
![screenshot 2018-07-09 at 11 12 09](https://user-images.githubusercontent.com/39521568/42441655-f5507604-8368-11e8-8175-c84a2bb6631a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] CrOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 69.0.3473.0

**Comment by kul3r4** [comment]
Thanks for report this, will investigate it.

**Comment by jamesshannon** [comment]
@Svenmay Thanks for reporting.

freegeoip.net, which I was using to get the lat/long from the client IP address, was migrated to a professional service, so I've signed up for ipstack.net and all is working.

**Comment by kul3r4** [comment]
Thanks! I can see that is working!

**Comment by Svenmay** [comment]
I can confirm that this is working again.

Thanks a lot for the super-speedy fix!

Cheers,
  Sven

**Comment by tsympov** [comment]
Seems like it's broken again...

**Comment by kul3r4** [comment]
@jamesshannon can you take a look? It seems the .json is not responding.

**Comment by jamesshannon** [comment]
Sorry about that.

I expect that this is because the geolocation API has hit its monthly free quota allotment. Generally, I've moved off of working with AMP so it might make sense to find someone else to maintain this (or turn it down).

Background: Previously (pre-July) this used to be a completely free service, then they switched to paid with a free quota model of 10k requests per month. We've gotten close to it for the past few months, and I have gotten lots of warnings, but this seems to be the first time that it's been shut down.

Oddly, GA stats for ABE show the pages gets around 1-2k requests per month so it's not clear where the 10k requests are coming from. The [code](https://glitch.com/edit/#!/caramel-wolf?path=server.js:28:6) doesn't seem to do anything especially stupid like making multiple API calls per request), but it could stand to be optimized (e.g., caching a specific IP address for 10 minutes to prevent new requests on manual refreshes).

Alternatively, there's a [50k request plan for $9.99](https://ipstack.com/product).

In any case, I'd look for someone else to own this. I can ask around on my old team, but the ABE "team" makes more sense.

**Comment by kul3r4** [comment]
Thanks James,
I will take a look at this

**Comment by philkrie** [comment]
Was it fixed since last reply? Looks like its down again, or has been down since September. We should get it back up, it's a great example that fits a lot of marketing use cases.
