### ISSUE TITLE
BUG: Amp-Sidebar "inline styles" error

### ISSUE THREAD

**Issue by orlov0562** [ampproject/amp-by-example#1341]
Hi there,

When I try to run amp-sidebar example, from [here](https://github.com/ampproject/amp-by-example/blob/master/src/20_Components/amp-sidebar.html) or [here](https://ampbyexample.com/components/amp-sidebar/preview/) in Chrome it produce next error in Developers Tools Console:

> Inline styles with `top`, `bottom` and other CSS rules are not supported yet for fixed or sticky elements (#14186). Unexpected behavior may occur.

Looks like the example doesn't match Chrome AMP requirements (LOL)

**Steps to reproduce**
- Open example from [here](https://github.com/ampproject/amp-by-example/blob/master/src/20_Components/amp-sidebar.html) or [here](https://ampbyexample.com/components/amp-sidebar/preview/) in Chrome
- Open Developers Tools, switch to Console tab
- Press three times on "Toogle sidebar"

**Current behavior**

Error: ```Inline styles with `top`, `bottom` and other CSS rules are not supported yet for fixed or sticky elements (#14186). Unexpected behavior may occur.```

![image](https://user-images.githubusercontent.com/1763904/42447520-daea5072-8382-11e8-8db8-448a46f95629.png)

**Expected behavior**
No errors

**Comment by fstanis** [comment]
This warning actually comes from the AMP runtime and it's safe to ignore. It's defined here:

https://github.com/ampproject/amphtml/blob/41087f3d009267ab8df97cf5577f257fc05778f9/src/service/fixed-layer.js#L474

Specifically, it's part of an experiment ([#11881](https://github.com/ampproject/amphtml/issues/11881)) to enable partial support for `style` attributes. Because `<amp-sidebar>` gets a `style` attribute when toggled, this triggers the (false positive) warning.

**Comment by madestroIT** [comment]
This is happening to me as well and it's not just logging errors. It disables the bar after it is hidden. JS errors occur and the sidebar can no longer be shown.

It can be seen [here](https://ampbyexample.com/components/amp-sidebar/preview/).

**Comment by karsten-eger** [comment]
It seems this problem is back again. We noticed it today in our navigation menu (in production no less!). The example madestrolT mentions does have the issue as well.

**Comment by fstanis** [comment]
Hi, this repo is no longer active since ampbyexample.com has been replaced by amp.dev.

If it's a sample issue, please report to https://github.com/ampproject/docs
If it's a component issue, please report to https://github.com/ampproject/amphtml

I'm unable to reproduce the issue that madestroIT explained in the sample at least, so we may need more information.

**Comment by karsten-eger** [comment]
Done so - thanks!

https://github.com/ampproject/amphtml/issues/22553
