### ISSUE TITLE
Add a quick note in AMPHTML Email examples

### ISSUE THREAD

**Issue by juliantoledo** [ampproject/amp-by-example#1350]
I think we should add a quick note in AMPHTML Email examples pointing to the spec:
https://github.com/ampproject/amphtml/blob/master/spec/amp-email-format.md

And also mention that Gmail is working on it's implementation:
https://www.blog.google/products/g-suite/bringing-power-amp-gmail/

**Comment by fstanis** [comment]
I moved the information you had in the "Hello World" sample so that it appears on top of every future sample that has the `"preview": "amp4email"` metadata and also added link to the blog post.

We should probably remove / revisit in the future, but I think this is a good / simple solution to make it consistent across our samples.
