### ISSUE TITLE
amp-fit-text padding breaks the amp-fit-text

### ISSUE THREAD

**Issue by IamAlta** [ampproject/amp-by-example#1454]
**Describe the bug**
The amp-fit-text places the text up against the containing box. 

To look nice, how about allowing CSS padding? Or some way to add space between the text and containing box?

**To Reproduce**
https://codepen.io/iamalta/pen/pZGozr

    <style amp-custom>
      div.fixedblock {
        text-align:center;
        margin: 58px 50px;
        height: 64px;
        width:  200px;
        background-color: yellow;
      }
      .p2{padding:2rem}
    </style>
    ...
    <div class="fixedblock"><amp-fit-text width="200" height="64" layout="responsive" class="p2">Life's Sayings Plaques and Stones</amp-fit-text></div>

I tried increasing width and height of .fixedblock with no success.

**Expected behavior**
Padding on left/right, top/bottom.

**Screenshots**
See above link

**Desktop (please complete the following information):**
any

**Smartphone (please complete the following information):**
not tested

**Additional context**

**Comment by kul3r4** [comment]
Hi, I think the main goal was to show how the amp-fit-text wraps the text and not sure how adding a padding may help with this. @sebastianbenz WDYT?

**Comment by sparhami** [comment]
The problem is that `<amp-fit-text>` creates a div, to measure the text at various sizes while trying to find the right one, but does not account for any CSS on the Element itself.

This will also cause problems if you have other CSS (e.g. if you use word-wrap: break-word), that might cause the text to lay out differently.

I think this should be possible to fix. In the short term, you can add any CSS styles that you want to a parent container of `<amp-fit-text>` (except for `line-height`).

I created an issue in the amphtml repo to track this.

**Comment by IamAlta** [comment]
Thank you @sparhami.
You guys are great! I appreciate all that you do.
