### ISSUE TITLE
Change like button width, now count number is cut off

### ISSUE THREAD

**Issue by tmdoit** [ampproject/amp-by-example#1544]
https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-facebook-like%2Fsource%2F

**Comment by kul3r4** [comment]
Hi, if you think there is a bug in the `amp-facebook-like` component please file a bug on https://github.com/ampproject/amphtml

**Comment by tmdoit** [comment]
There is no bug in component just in code written in playground editor - count number doesn't fit in like button.

**Comment by kul3r4** [comment]
It seems to me that you cannot make the width any smaller otherwise there will not be enough space for the content.
@aghassemi to confirm if you have more context around [https://github.com/ampproject/amphtml/commit/9a1bfaf5319bf6fefabc262e2a9b1c2a86e206e2#diff-fe1d02b89b7d68804f8244377159bbc3](https://github.com/ampproject/amphtml/commit/9a1bfaf5319bf6fefabc262e2a9b1c2a86e206e2#diff-fe1d02b89b7d68804f8244377159bbc3)

**Comment by aghassemi** [comment]
FB's like embed component only supports `small` or `large`  sizes https://developers.facebook.com/docs/plugins/like-button#settings . I suggest using a layout=responsive or fixed-height for the ABE sample. `amp-facebook-like` height automatically changes after load so you just need to make sure there is enough width

**Comment by tmdoit** [comment]
I don't know if we are clear, I'm talking about cosmetic change for UX when learning from examples, **now is:**
![screen shot 2018-10-08 at 20 19 38](https://user-images.githubusercontent.com/26081817/46628284-5982fb80-cb3d-11e8-8a62-6be8bf7764b4.png)
**Could be:**
![screen shot 2018-10-08 at 20 31 22](https://user-images.githubusercontent.com/26081817/46628322-7d464180-cb3d-11e8-8d83-8a3e020be783.png)

**Comment by kul3r4** [comment]
Ok, thanks for explaining, feel free to send a PR to increase the width.

**Comment by tmdoit** [comment]
https://github.com/ampproject/amp-by-example/pull/1553
