### ISSUE TITLE
Validate sample files

### ISSUE THREAD

**Issue by jmadler** [ampproject/amp-by-example#161]
A number of the documents under src/*/*.html are invalid AMP.  It might make sense to validate these as part of gulp validate, and also to modify them to be valid.

**Comment by kul3r4** [comment]
Could you enumerate which ones are invalid?

**Comment by sebastianbenz** [comment]
We already validate the generated sample files (and this is what counts). AFAIK all samples are valid - only the ones marked as experimental are not validated as they the validator is often not yet up to date. Most of the samples in src are missing the canonical link which is generated automatically. Hence validation doesn't really make sense here.

**Comment by jmadler** [comment]
Only amp-social-share is valid.  The rest seem to be missing 'link rel=canonical'.

**Comment by kul3r4** [comment]
Hi, the generated pages have the link rel=canonical.
For example, I checked [amp-facebook](view-source:https://ampbyexample.com/components/amp-facebook/,) and it contains: <link rel="canonical" href="https://ampbyexample.com/components/amp-facebook/" >.

**Comment by jmadler** [comment]
Yes, but the link rel=canonical isn't in the source pane of the sample

**Comment by jkingyens** [comment]
I am re-opening this because I think there is a deeper issue here. @Gregable, myself and @jmadler have assumed the files in "src" should be valid AMP at one point or another. I think we should make a change that makes it more clear these files are not intended to be valid AMP. It will benefit all future users who are stumped by this. Ideas:

1) change the extension of the files from .html to html.input to re-enforce the idea that these files need to be processed to become html.
2) remove the <html ⚡><head>... from the src files to emphasize the source are just "fragments" that are combined during build to create the final AMP files.

I think 2) is best as it also removes the confusion around where the data comes from to produce the output AMPs. Right now it appears like the <html ⚡><head>... is coming from the source when in fact it is being pulled in from other snippets.

**Comment by kul3r4** [comment]
Fixed by #234
