### ISSUE TITLE
Some examples fail validation

### ISSUE THREAD

**Issue by dknecht** [ampproject/amp-by-example#320]
https://ampbyexample.com/components/amp-form - https://validator.ampproject.org/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-form
https://ampbyexample.com/components/amp-fx-flying-carpet - https://validator.ampproject.org/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-fx-flying-carpet
https://ampbyexample.com/components/amp-live-list - https://validator.ampproject.org/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-fx-flying-carpet
https://ampbyexample.com/components/amp-sidebar - https://validator.ampproject.org/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-sidebar
https://ampbyexample.com/samples_templates/housing/preview/ - https://validator.ampproject.org/#url=https%3A%2F%2Fampbyexample.com%2Fsamples_templates%2Fhousing%2Fpreview%2F

**Comment by kul3r4** [comment]
Hi,
when samples contain experimental component, it's normal that they don't validate.
[amp-form](https://ampbyexample.com/components/amp-form/) is experimental, so all the examples containing it will fail the validation, such us [amp-form](https://ampbyexample.com/components/amp-form/) and [housing](https://ampbyexample.com/samples_templates/housing/preview/).

amp-fix-flying-carpet is experimental, see [doc](https://www.ampproject.org/it/docs/reference/extended/amp-fx-flying-carpet.html)
amp-live-list is experimental, see [doc](https://github.com/ampproject/amphtml/blob/master/extensions/amp-live-list/amp-live-list.md)

amp-side-bar should work, but probably the problem is that we are using that twice in the page (for the left menu and the example itself). Please create an issue just for this.

Hope it helps.

**Comment by sebastianbenz** [comment]
The amp-sidebar sample is tricky to get to validate. There are two problems:

1. amp-sidebar needs to be the first element after the body tag (see #167)
2. only one sidebar is allowed per page and we have two together with the ABE navigation menu.

**Comment by emestud** [comment]
Would it be possible to use an amp-iframe for the script tag (experimental mode)?
This would also allow to have the amp-sidebar as a child of <body> for example in this page: https://ampbyexample.com/samples_templates/product/preview/

**Comment by sebastianbenz** [comment]
We can't use an iframe for triggering experimental mode -> experimental flag is stored via cookie  which needs to be set for the document host.

Fixing samples with amp-sidebar needs to be handled during the example compilation step.
