### ISSUE TITLE
Request: linked carousel / lightbox example w/ amp-bind

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amp-by-example#578]
This example would use amp-bind to demo the behavior of a linked lightbox and carousel. I could see it appearing in a few different places, including amp-bind, advanced carousel pages, the e-commerce sample, or on its own. I don't have a strong opinion either way, but it might fit easiest on the advanced carousel page.

User experience would be:

1. User swipes to image N in amp-carousel in main content of page
2. User taps on image N, to enter lightbox mode
2.1 Lightbox mode is a modal on top of the main content, displaying image N as a full-bleed image, on a black background, with an "X" in the upper left-hand corner to exit back to the main page.
3. User can swipe inside of lightbox mode between images — swipes to image N+n
4. When user taps "X", user exits back to the main page content. Back on the main page, the carousel displays image N+n (it is sync'd with the carousel that appeared inside of the lightbox mode)

Can't find a great example at the moment, but roughly like [this image carousel](https://www.amazon.com/KitchenAid-Professional-KSM6573CER-Stand-Empire/dp/B00PZU3AEI?pf_rd_p=ddf35be3-0e94-4f3f-92cd-c74d472da57e&pf_rd_s=grid-unrec-2&pf_rd_t=Gateway&pf_rd_i=mobile&pf_rd_m=ATVPDKIKX0DER&pf_rd_r=RFSXDXETS0HRFCMDJ3HQ&pf_rd_r=RFSXDXETS0HRFCMDJ3HQ&pf_rd_p=ddf35be3-0e94-4f3f-92cd-c74d472da57e&m=ATVPDKIKX0DER&ref_=gwm_dotd_p), except the carousel on the main page tracks your position in the lightbox carousel. 

Let me know if this doesn't make sense — it's a little hard to describe without visuals :)

/cc @choumx @kul3r4 @aghassemi @sebastianbenz

**Comment by aghassemi** [comment]
Lightbox 2.0 (when done :disappointed:) will provide all of this functionality and more. This UX should still be possible today with bind, carousel and lightbox but will fall short on a few things:
1- User will lose some image-viewing functionality in lightbox (e.g. zoom, swipe up/down to dismiss). This is because image-lightbox does not support swiping between multiple images and regular carousel with images doesn't provide image-viewing functionality.
2- There won't be any transition animations when tapping an image until it opens in the lightbox (for the same reason as above, only image-lightbox provides transition animations)
3- Won't work nicely for other media types like videos ( since carousel in the lightbox and carousel in the page would need to keep two separate instances of the same video and the video state can not be synced between those two instances, ever, even with bind. This is because those states are private and out of AMP's reach. Only solution is to reuse the same instance which is what Lightbox 2.0 does)

I think it is still a good idea to provide this example with the caveat that the final Lightbox 2.0 will replace it as the correct solution.

**Comment by sebastianbenz** [comment]
I'm a bit torn whether it makes sense to turn this into a sample then or not. Might make sense to have a simple generic amp-bind with amp-lightbox sample instead.

**Comment by ericlindley-g** [comment]
Interesting — what would a generic amp-bind with amp-lightbox sample look like?

**Comment by gEndelf** [comment]
Example: https://ampbyexample.com/advanced/image_galleries_with_amp-carousel/#linking-carousels-with-amp-bind
But it seems it doesn't work

**Comment by sebastianbenz** [comment]
@gEndelf did you enable the experiment & dev channel?

**Comment by kul3r4** [comment]
@aghassemi when I use `amp-carousel` + `amp-image-lightbox` I get:

> 0.js:80 Unsupported element:  AMP-CAROUSEL
> he @ v0.js:80
> log.js:523 Uncaught Error: Action execution failed: AMP-IMAGE-LIGHTBOX activate: Unsupported element: AMP-CAROUSEL​​​ _reported_

Is this a bug or not in the spec?
@ericlindley-g FYI

**Comment by aghassemi** [comment]
:) just for the all-new `amp-lightbox-lightbox` next week :) j/k
