### ISSUE TITLE
amp-selector examples cause slight vertical re-size on selection

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amp-by-example#603]
Due to the border style, selecting/de-selecting items in the [amp-selector examples](https://ampbyexample.com/components/amp-selector/) causes a slight vertical resize. (Most evident in the forms list example at the very bottom of the page). 

Probably a few ways to solve this, but one is just to choose a single outline style rather than having a border as well.

**Comment by sebastianbenz** [comment]
Wow - that's indeed ugly. Wondering why I never noticed...

On Tue, Feb 7, 2017 at 4:26 PM ericlindley-g <notifications@github.com>
wrote:

Due to the border style, selecting/de-selecting items in the amp-selector
examples <https://ampbyexample.com/components/amp-selector/> causes a
slight vertical resize. (Most evident in the forms list example at the very
bottom of the page).

Probably a few ways to solve this, but one is just to choose a single
outline style rather than having a border as well.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ampproject/amp-by-example/issues/603>, or mute the
thread
