### ISSUE TITLE
Add to shopping cart without page reload

### ISSUE THREAD

**Issue by jasti** [ampproject/amp-by-example#629]
Similar to https://github.com/ampproject/amp-by-example/issues/369 but it'd be great to have a sample where adding a product to cart leads to updating the shopping cart without a page reload using amp-form (possibly using XHR post passing the CID as a hidden field) and amp-bind.
CC @kul3r4

**Comment by sebastianbenz** [comment]
Would you include a separate shopping cart view as well?

**Comment by jasti** [comment]
As in clicking on the updated cart leading to a new page with the shopping cart products? That would be great.

**Comment by cramforce** [comment]
While this is nice, I think we should recommend shopping cart flows that are guaranteed to not fail. By reloading to origin site, we work around all cookie issues.

Speaking of nice: Amazon doesn't do it, because it is bad on mobile. Why would you want to stay on the page after clicking add-to-cart? Going to a new page is much better, because it is a clearer signal for the user and a better surface for up and cross selling.

**Comment by jasti** [comment]
Fair point. Also see that the 'redirect after add to cart' example is working now.
https://ampbyexample.com/samples_templates/product/preview/

Closing this.
