### ISSUE TITLE
Embedding Gist code snippets

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-by-example#90]

**Comment by jkingyens** [comment]
Gists do not work with iframes, so we'll need a custom component to represent these. There are multiple issues in the core amphtml repo related to creating this ([2412](https://github.com/ampproject/amphtml/issues/2412) and [829](https://github.com/ampproject/amphtml/issues/829)). 

It sounds like we'll want a solution that renders on the server and served in an iframe.

**Comment by edm00se** [comment]
An imperfect example is to follow the approach of [setting up Disqus with AMP](https://github.com/disqus/disqus-install-examples/tree/master/google-amp#how-to-install), which effectively loads the scripts on another page of a different, owned domain, passing relevant parameters via query params, to get around the _no scripts_ situation. Ideally there should be something more AMP official.

If someone else is looking for a solution, what's needed with the approach I mentioned is:

1. an HTML file for the gist embedding on the alternate domain
2. use as an &lt;amp-iframe&gt;

Example:

<details><summary>HTML file to handle loading of gist, passed by URL query params</summary><p>
sample live at <a href="https://github.com/edm00se/edm00se.github.io/blob/master/gist_embed.html">gist_embed.html</a>, &lt;body&gt; contents shown

---

```html
<div id="gist_embed"></div>
<script>
  function receiveMessage(event){
    if (event.data) {
      var msg;
      try {
        msg = JSON.parse(event.data);
      } catch (err) {
        // Do nothing
      }
      if (!msg)
        return false;

      if (msg.name === 'resize') {
        window.parent.postMessage({
          sentinel: 'amp',
          type: 'embed-size',
          height: msg.data.height
        }, '*');
      }
    }
  }
  window.addEventListener('message', receiveMessage, false);
</script>
<script>
  function getQueryVariable(variable) {
    var query = window.location.search.substring(1);
    var vars = query.split('&');
    for (var i=0;i<vars.length;i++) {
    var pair = vars[i].split("=");
      if(pair[0] == variable){
        return pair[1];
      }
    }
    return(false);
  }
  (function() {
    var d = document, s = d.createElement('script');
    var id = getQueryVariable("id");
    var fName = getQueryVariable("fileName");

    var mySrc = 'https://gist.github.com/' + id + '.js';
    if( fName != '' ){
      mySrc += '?file=' + fName;
    }
    s.src = mySrc;
    s.type = 'text/javascript';

    document.getElementById('gist_embed').appendChild(s);

  })();
</script>
<script defer>
  window.setTimeout(function(){
    var val = document.getElementById('gist_embed').scrollHeight;
    // console.log('should reset iframe height to ' + val);
    window.parent.postMessage({
      sentinel: 'amp',
      type: 'embed-size',
      height: val
    }, '*');
  }, 500);
</script>
```
</p></details>

<details><summary>the &lt;amp-iframe&gt; to use</summary><p>

---

```html
<amp-iframe width="600" height="100"
  layout="responsive"
  sandbox="allow-scripts allow-same-origin allow-modals allow-popups"
  resizable
  frameborder="0"
  src="https://some-url.com/path/to/gist_embed.html">
  <div overflow tabindex="0" role="button" aria-label="Gist Embed">Gist Embed</div>
</amp-iframe>
```

I use the &lt;amp-iframe&gt; in an include snippet (for a Jekyll based site), with parameters of gist id and file (if any specified, otherwise shows all). To use it like this with a Jekyll site:
- put the above into `_includes/gist.html`
- set `gist_embed_url` to the value where you park your `gist_embed.html` from step 1
- replace the `src` with:
  - `{{ site.gist_embed_url }}?id={{ include.id }}{% if include.file %}&fileName={{ include.file }}{% endif %}`
  - ([example from my blog](https://github.com/edm00se/DevBlog/blob/gh-pages/_includes/gist.html))
- implement in your posts or pages with `{% include gist.html id="some-gist-id" file="some file" %}` (leaving out the `file="..."` will show all files)
</p></details>

**Comment by sebastianbenz** [comment]
@edm00se would you be willing to create a sample for this? We already have a different domain for these use cases in the [here](https://github.com/ampproject/amp-by-example/tree/master/api/iframe).

**Comment by edm00se** [comment]
I'll have a look when I get a chance.; might be over the weekend.

**Comment by edm00se** [comment]
Correction, whenever I can find time. 😬

**Comment by edm00se** [comment]
It would appear I've ~~procrastinated enough~~ been too busy. This feature appears to be making its way into AMP as a standard tag; any examples should probably follow that implementation.
https://github.com/ampproject/amphtml/pull/8263
